import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        browser: true,
        es2021: true,
        node: true
      }
    },
    rules: {
      'import/no-extraneous-dependencies': 'off',
      'import/extensions': 'off',
      'import/no-unresolved': 'off',
      'no-console': 'off',
      'prefer-destructuring': ['error', { object: true, array: false }],
      'vue/no-unused-components': 'error',
      'no-self-compare': 'error',
      'no-unused-vars': 'error',
      'no-empty': 'error',
      'no-lone-blocks': 'error',
      'no-irregular-whitespace': 'error',
      'no-return-assign': 'error',
      'no-inner-declarations': 'error',
      'vue/multi-word-component-names': 'off',
      'no-debugger': 'error',
      'no-duplicate-case': 'error',
      'no-extra-parens': 'off',
      'no-func-assign': 'error',
      'no-unreachable': 'error',
      curly: 'error',
      eqeqeq: 'error',
      'no-else-return': 'error',
      'no-multi-spaces': 'error',
      'no-redeclare': 'error',
      'no-return-await': 'error',
      'no-self-assign': 'error',
      'no-useless-catch': 'error',
      'no-useless-return': 'error',
      'no-shadow': 'off',
      'no-delete-var': 'off',
      'array-bracket-spacing': 'error',
      'brace-style': 'error',
      camelcase: 'error',
      indent: 'off',
      'max-nested-callbacks': ['error', 3],
      'max-params': ['error', 3],
      'max-statements-per-line': ['error', { max: 1 }],
      'no-lonely-if': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multiple-empty-lines': 'error',
      semi: ['error', 'never'],
      'space-before-blocks': 'error',
      'space-in-parens': 'error',
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'spaced-comment': 'error',
      'switch-colon-spacing': 'error',
      'arrow-spacing': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'prefer-rest-params': 'error',
      'no-useless-escape': 'error',
      'no-prototype-builtins': 'error',
      'no-fallthrough': 'error',
      'no-extra-boolean-cast': 'error',
      'no-case-declarations': 'error',
      'no-async-promise-executor': 'error'
    }
  },
  {
    ignores: [
      '*.sh',
      'node_modules',
      '*.md',
      '*.woff',
      '*.ttf',
      '.vscode',
      '.idea',
      'dist',
      'public',
      'docs',
      '.husky',
      '.local',
      'bin',
      'Dockerfile',
      'yarn.lock',
      'app/assets',
      '.nuxt',
      '.output'
    ]
  }
)